// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBq38AHhwRndZRM9fgoRHpaZlsGToXOM',
    appId: '1:472022562371:web:c58437810447767e0446f6',
    messagingSenderId: '472022562371',
    projectId: 'flutter-budget-planner',
    authDomain: 'flutter-budget-planner.firebaseapp.com',
    storageBucket: 'flutter-budget-planner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8w2486Bu3yO4Ikc65wdk1h52YcoYW3Y',
    appId: '1:472022562371:android:6ca69e0863bf2b650446f6',
    messagingSenderId: '472022562371',
    projectId: 'flutter-budget-planner',
    storageBucket: 'flutter-budget-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZIwo-gHe0_0PCdgu5qg7AgpHYe7iuNzU',
    appId: '1:472022562371:ios:f4eb8ee8b86797bd0446f6',
    messagingSenderId: '472022562371',
    projectId: 'flutter-budget-planner',
    storageBucket: 'flutter-budget-planner.appspot.com',
    iosBundleId: 'com.example.budgetplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZIwo-gHe0_0PCdgu5qg7AgpHYe7iuNzU',
    appId: '1:472022562371:ios:f4eb8ee8b86797bd0446f6',
    messagingSenderId: '472022562371',
    projectId: 'flutter-budget-planner',
    storageBucket: 'flutter-budget-planner.appspot.com',
    iosBundleId: 'com.example.budgetplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBq38AHhwRndZRM9fgoRHpaZlsGToXOM',
    appId: '1:472022562371:web:1909291930b789b70446f6',
    messagingSenderId: '472022562371',
    projectId: 'flutter-budget-planner',
    authDomain: 'flutter-budget-planner.firebaseapp.com',
    storageBucket: 'flutter-budget-planner.appspot.com',
  );

}